# Generated by Django 2.0.2 on 2018-02-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('sinopse', models.TextField(help_text='The item synopsis.', verbose_name='Sinopse')),
                ('card_img', models.ImageField(blank=True, upload_to='danzou/anime', verbose_name='Img file')),
                ('card_img_url', models.URLField(blank=True, unique=True, verbose_name='Img url')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Anime',
                'verbose_name_plural': 'Animes',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categorys',
            },
        ),
        migrations.CreateModel(
            name='Ep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('ep_number', models.PositiveIntegerField(verbose_name='Ep number')),
                ('url_download', models.URLField(unique=True, verbose_name='Link download')),
                ('file_duration', models.CharField(max_length=50, verbose_name='Duration')),
                ('file_subtitles', models.CharField(max_length=50, verbose_name='Subtitles')),
                ('file_size', models.CharField(max_length=50, verbose_name='Size')),
                ('file_format', models.CharField(max_length=50, verbose_name='Format')),
                ('file_audio', models.CharField(max_length=50, verbose_name='Audio')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ep',
                'verbose_name_plural': 'Eps',
            },
        ),
        migrations.AddField(
            model_name='anime',
            name='category',
            field=models.ManyToManyField(to='api.Category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='anime',
            name='ep',
            field=models.ManyToManyField(blank=True, to='api.Ep', verbose_name='Eps'),
        ),
    ]
